### ISSUE TITLE
Trouble Flipping the Ace

### ISSUE THREAD

**Issue by awdriggs** [awdriggs/blackjack#1]
I'm having trouble with the function that flips the ace. It is setValue function on line 36 of the the hand.js file.

I worked on this with Will today. 

What is happening is that the Ace is never setting itself to 1, it is always an 11. The function is supposed to set set the value of the face cards to 10, the value of the number cards to their numeric value. If the value is greater than 10, then the ace is supposed to be a one, otherwise it is an 11.

I had added an isNaN to filter out the ace, if I don't have this it treats the ace as a string.

I'm calling this function every time that I do a hit to make sure the cards don't go over 21.

Does it have something to do with the order of the cards when it is stepping through the cards array?

**Comment by DBrodsky90** [comment]
Shouldn't line 46 be in a else? I think otherwise it runs that line also.

**Comment by awdriggs** [comment]
I rewrote this function as two different functions. 

```

Hand.prototype.getValue = function() {
    var value = this.aceFlipper(11);
    if(value <= 21){
        this.value = value;
    } else {
        this.value = this.aceFlipper(1);
    }

    return this.value;
};

Hand.prototype.aceFlipper = function(aceControl) {
    checkValue = 0; 
    aceValue = aceControl;

    for(var i = 0; i < this.cards.length; i++){
        if(this.cards[i].value === "Ace"){
            checkValue += aceValue;
        } else if(this.cards[i].value === "King"|| this.cards[i].value === "Queen" || this.cards[i].value === "Jack"){
            checkValue += 10
        } else {
            checkValue += this.cards[i].value;
        } 
    }

    return checkValue;
};
```
